defmodule AshIceberg.Catalog do
  @moduledoc """
  Behaviour and macro for defining Iceberg catalog modules.

  An Iceberg catalog module holds connection settings for one catalog
  (REST or filesystem) and starts a `AshIceberg.Connection` GenServer
  that keeps a live DuckDB session ready for queries.

  ## Usage

      defmodule MyApp.IcebergCatalog do
        use AshIceberg.Catalog, otp_app: :my_app
      end

      # In your supervision tree:
      children = [
        MyApp.IcebergCatalog
      ]

      # config/config.exs (REST catalog)
      config :my_app, MyApp.IcebergCatalog,
        type: :rest,
        uri: "http://localhost:8181",
        token: "my-token",
        warehouse: "s3://my-bucket/warehouse",
        aws_region: "us-east-1",
        aws_access_key_id: System.get_env("AWS_ACCESS_KEY_ID"),
        aws_secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY")

      # config/config.exs (filesystem)
      config :my_app, MyApp.IcebergCatalog,
        type: :filesystem,
        path: "/data/iceberg/warehouse"

  ## Configuration Keys

  | Key | Type | Description |
  |-----|------|-------------|
  | `type` | `:rest` \\| `:filesystem` | Catalog backend (default `:rest`) |
  | `uri` | `string` | REST catalog base URL |
  | `token` | `string` | Bearer token for REST auth |
  | `warehouse` | `string` | S3 or file warehouse root |
  | `path` | `string` | Local warehouse path (`:filesystem` type) |
  | `aws_region` | `string` | AWS region for S3 |
  | `aws_access_key_id` | `string` | AWS access key |
  | `aws_secret_access_key` | `string` | AWS secret key |
  | `pool_size` | `pos_integer` | DuckDB connection pool size (default 1) |
  """

  @doc "Returns the application config map for this catalog."
  @callback config() :: map()

  @doc "Returns the table location string from the REST catalog for `namespace/table`."
  @callback table_location(namespace :: String.t(), table :: String.t()) ::
              {:ok, String.t()} | {:error, term()}

  @doc false
  defmacro __using__(opts) do
    quote bind_quoted: [opts: opts] do
      @behaviour AshIceberg.Catalog

      @otp_app opts[:otp_app] ||
                 raise(ArgumentError, "AshIceberg.Catalog requires the :otp_app option")

      @impl AshIceberg.Catalog
      def config do
        env_config = Application.get_env(@otp_app, __MODULE__, [])
        # Ensure catalog_name is always set so the ATTACH name matches the
        # table-reference name generated by QueryBuilder.
        env_config
        |> Map.new()
        |> Map.put_new(:catalog_name, AshIceberg.Catalog.catalog_name(__MODULE__))
      end

      @impl AshIceberg.Catalog
      def table_location(namespace, table) do
        # Delegate to the module-level function so the type checker cannot
        # narrow the `cfg` type and generate spurious unreachable-clause warnings.
        AshIceberg.Catalog.resolve_table_location(config(), namespace, table)
      end

      def child_spec(opts) do
        pool_size = config()[:pool_size] || 1

        if pool_size == 1 do
          %{
            id: __MODULE__,
            start:
              {AshIceberg.Connection, :start_link,
               [[catalog: __MODULE__, name: __MODULE__] ++ opts]},
            type: :worker,
            restart: :permanent
          }
        else
          children =
            for i <- 0..(pool_size - 1) do
              name = AshIceberg.Catalog.worker_name(__MODULE__, i)
              %{
                id: name,
                start:
                  {AshIceberg.Connection, :start_link,
                   [[catalog: __MODULE__, name: name] ++ opts]},
                type: :worker,
                restart: :permanent
              }
            end

          %{
            id: __MODULE__,
            start: {Supervisor, :start_link, [children, [strategy: :one_for_one]]},
            type: :supervisor
          }
        end
      end

      @doc "Execute a SQL string against this catalog's DuckDB connection (pool-aware)."
      def query(sql) do
        worker = AshIceberg.Catalog.pick_worker(__MODULE__)
        AshIceberg.Connection.query(worker, sql)
      end

      def start_link(opts \\ []) do
        pool_size = config()[:pool_size] || 1

        if pool_size == 1 do
          AshIceberg.Connection.start_link([catalog: __MODULE__, name: __MODULE__] ++ opts)
        else
          children =
            for i <- 0..(pool_size - 1) do
              name = AshIceberg.Catalog.worker_name(__MODULE__, i)
              %{
                id: name,
                start:
                  {AshIceberg.Connection, :start_link,
                   [[catalog: __MODULE__, name: name] ++ opts]},
                type: :worker,
                restart: :permanent
              }
            end

          Supervisor.start_link(children, strategy: :one_for_one)
        end
      end

      defoverridable config: 0, table_location: 2
    end
  end

  @doc """
  Returns the DuckDB-side catalog name derived from a catalog module.

  Used when building qualified table references (`catalog.namespace.table`).
  """
  def catalog_name(catalog_module) when is_atom(catalog_module) do
    # Prefer the catalog_name set in the catalog's config; fall back to
    # snake_casing the last segment of the module name.
    with true <- function_exported?(catalog_module, :config, 0),
         %{catalog_name: name} when is_binary(name) <- catalog_module.config() do
      name
    else
      _ ->
        catalog_module
        |> Module.split()
        |> List.last()
        |> Macro.underscore()
        |> String.replace(~r/[^a-z0-9_]/, "_")
    end
  end

  @doc "Returns the registered name for pool worker `index` of `catalog_module`."
  def worker_name(catalog_module, index) when is_integer(index) do
    :"#{catalog_module}_#{index}"
  end

  @doc """
  Returns the atom name of the appropriate pool worker for the calling process.

  When `pool_size` is 1, returns the catalog module atom itself. For larger
  pools, picks a worker via process-hash affinity so the same caller always
  hits the same DuckDB connection (improves cache locality).
  """
  def pick_worker(catalog_module) do
    pool_size = catalog_module.config()[:pool_size] || 1

    if pool_size == 1 do
      catalog_module
    else
      worker_name(catalog_module, rem(:erlang.phash2(self()), pool_size))
    end
  end

  @doc false
  def resolve_table_location(cfg, namespace, table) do
    case cfg do
      %{type: :filesystem, path: path} ->
        {:ok, Path.join([path, namespace, table])}

      %{type: :rest} = rest_cfg ->
        case AshIceberg.Catalog.RestClient.load_table(rest_cfg, namespace, table) do
          {:ok, %{"metadata-location" => loc}} -> {:ok, loc}
          {:ok, %{"metadata" => %{"location" => loc}}} -> {:ok, loc}
          {:error, _} = err -> err
        end

      %{warehouse: warehouse} when is_binary(warehouse) ->
        {:ok, "#{String.trim_trailing(warehouse, "/")}/#{namespace}/#{table}"}

      _ ->
        {:error, "Cannot determine table location from catalog config"}
    end
  end
end
